### ISSUE TITLE
get some weird message while play video stream

### ISSUE THREAD

**Issue by Brli** [i-rinat/libvdpau-va-gl#20]
[VS] error (softVdpVideoSurfaceGetBitsYCbCr): not implemented conversion VA FOURCC � -> VDP_YCBCR_FORMAT_NV12
[VS] error (softVdpVideoSurfaceGetBitsYCbCr): not implemented conversion VA FOURCC � -> VDP_YCBCR_FORMAT_NV12
[VS] error (softVdpVideoSurfaceGetBitsYCbCr): not implemented conversion VA FOURCC � -> VDP_YCBCR_FORMAT_NV12
[VS] error (softVdpVideoSurfaceGetBitsYCbCr): not implemented conversion VA FOURCC � -> VDP_YCBCR_FORMAT_NV12
[VS] error (softVdpVideoSurfaceGetBitsYCbCr): not implemented conversion VA FOURCC  -> VDP_YCBCR_FORMAT_NV12
[VS] warning (softVdpDeviceDestroy): non-zero reference count (14). Trying to free child objects.

although the stream play and render under hw accelerate fine, just be curious if this is harmless?

**Comment by genodeftest** [comment]
Where can this issue be fixed? If it is an external bug, where is the bug? I am seeing the same issue in VLC on Intel iGPUs and video doesn't play at all either.

**Comment by i-rinat** [comment]
> Where can this issue be fixed? If it is an external bug, where is the bug?

In either VA driver (i965-va-driver, recent fglrx versions have native VA-API driver too) or in VA-API compatibility layer (xvba-va-driver).
In either case, there is still possibility that error is hidden somewhere else, or even in `libvdpau-va-gl`. No one can be sure.
