### ISSUE TITLE
fails to play videos using VLC on Fedora on Intel iGPU

### ISSUE THREAD

**Issue by genodeftest** [i-rinat/libvdpau-va-gl#46]
I have a computer with an Intel 1st generation core i5 CPU and iGPU.

Using VLC media player without libvdpau-va-gl works fine but gives some warnings when starting to play a file:  `Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory`

With libvdpau-va-gl 0.3.4 installed I get no video (audio still works) but loads of these error messages:
```
[VS] error (vdpVideoSurfaceGetBitsYCbCr): not implemented conversion VA FOURCC � -> VDP_YCBCR_FORMAT_YV12
[00007f93300be948] vdpau_chroma filter error: video surface export failure: VDP_STATUS_INVALID_Y_CB_CR_FORMAT
```
and
```
[h264 @ 0x7f9314c0ee80] hardware accelerator failed to decode picture
```
and some more, rarely occurring errors:
```
[00007f93300c5558] blend blend error: no matching alpha blending routine (chroma: YUVA -> VDV0)
[00007f93300c5558] core blend error: blending YUVA to VDV0 failed
```

**Comment by i-rinat** [comment]
>  Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory

That's fine, because VLC have direct VA-API support. It's just a notification about VLC tried to open VDPAU driver, but didn't found appropriate.

> VA FOURCC �

FourCC should consist of four readable characters, i.e. NV12, YV12, I420, and so on. Here you see VA driver returned something wrong.

> YUVA to VDV0

I think `YUVA` is YUV with alpha channel. But I don't known what `VDV0` format is. Googling doesn't give anything about it.

**Comment by genodeftest** [comment]
The VA-API support in VLC isn't working either, gets VLC to freeze the whole desktop session (GNOME).
Any way to help?

**Comment by i-rinat** [comment]
> gets VLC to freeze the whole desktop session

The culprit is either VA driver or hardware.

> Any way to help?

It's worth to report to [libva mailing list](http://lists.freedesktop.org/mailman/listinfo/libva) or to [freedesktop.org bugzilla](https://bugs.freedesktop.org/buglist.cgi?component=intel&product=libva&resolution=---).

**Comment by mr-sk** [comment]
Just wanted to note that I fixed this error by changing VLC to the "direct VA-API" support, which in turn used the i965 intel driver. Not sure how this fix would translate to other players (mplayer, ...).

**Comment by genodeftest** [comment]
With current mesa 10.6.9 installed I cannot reproduce this issue any more.
