### ISSUE TITLE
Unable to play some video with VLC (hardware accelerator failed to decode picture)

### ISSUE THREAD

**Issue by vincentbernat** [i-rinat/libvdpau-va-gl#50]
Hey!

I got reports of this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?archive=yes&bug=813370

It's very easy to reproduce with 0.3.4 installed and the provided video file. I have looked a bit at the commits that were added after 0.3.4 but didn't see anything related. I can try with the current HEAD if needed.

**Comment by i-rinat** [comment]
Hi.
There is noticeable artifacts in video at about `00:00:01`, perhaps video stream is broken. I've tried to play it though vaapi path in `mpv` and also through vdpau path with help of `libvdpau-va-gl` on both `mplayer` and `mpv`. And all those were fine, without lockups or error messages. It could be hardware dependent. I tested on Intel HD 4000 (embedded graphics in i7-3632qm processor).

Could you check on your hardware how
```
mpv --hwdec=vaapi --vo=gl  big_buck_bunny_480p_H264_AAC_25fps_1800K_short.MP4
```
works, please?

**Comment by vincentbernat** [comment]
Your command works fine for me:

```
mpv --hwdec=vaapi --vo=gl  big_buck_bunny_480p_H264_AAC_25fps_1800K_short.MP4
Driver 'gl' has been replaced with 'opengl'!
Playing: big_buck_bunny_480p_H264_AAC_25fps_1800K_short.MP4
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
File tags:
 Artist: created with SUPER(C).v2011.bld.49
 Comment: 14:06:42
 Title: big_buck_bunny_480p_surround-fix.avi_041.AVI.MP4
libva info: VA-API version 0.38.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
AO: [pulse] 44100Hz stereo 2ch float
Using hardware decoding (vaapi).
VO: [opengl] 854x480 vaapi
AV: 00:00:01 / 00:00:04 (27%) A-V:  0.000
```

**Comment by i-rinat** [comment]
Then it's bug in libvdpau-va-gl indeed. I'll try to dig further.

**Comment by i-rinat** [comment]
Oh, I've tried VLC (2.2.2-3+b1, Debian testing), and now can see the same bug. Now there are higher chances to find out what's happening.

**Comment by i-rinat** [comment]
Just to be sure. Does
```
mpv --hwdec=vdpau --vo=vdpau  big_buck_bunny_480p_H264_AAC_25fps_1800K_short.MP4
```
show video?

**Comment by vincentbernat** [comment]
Yes, it works too. So, this may be a bug in VLC?

**Comment by vincentbernat** [comment]
Great that you found the source. Would you like me to report the bugs to VLC devs?

**Comment by i-rinat** [comment]
I don't see similar code in VLC's master branch. Most probably they've fixed it already. But on the other hand that version tries to use VDPAU part which is not implemented in libvdpau-va-gl, so I can't be sure.

**Comment by vincentbernat** [comment]
I have asked one of VLC dev to have a look.

**Comment by i-rinat** [comment]
Current versions of VLC don't have the issue. "Fixing" commit was https://github.com/videolan/vlc/commit/c61b433aae0f31b7a8ccd0830e12c0bc08b1b3fd#diff-4e89dea6d2b66dcaac6f076da940fba2L400. Note, they started to compare surfaces geometry with coded width and height from `AVCodecContext` structure.

Newer VLC versions started to use another bit of VDPAU, so I've added required mockup code in https://github.com/i-rinat/libvdpau-va-gl/commit/e10ef7a3df602d5259cf360b78c6d5ef87adde4e. It doesn't work they way it should work, but should be fine anyway.

**Comment by i-rinat** [comment]
Also found that `mpv` tries Constrained Baseline profile, and falls back to software decoding if profile is not available. 8c26e71a616c3f10cd37c46a52495228d79d8e00 fixes that.

**Comment by vincentbernat** [comment]
Thanks! A release in the next weeks would be welcome (otherwise, I will use a git snapshot).

**Comment by i-rinat** [comment]
Here it is: https://github.com/i-rinat/libvdpau-va-gl/releases/tag/v0.3.6

**Comment by vincentbernat** [comment]
Thanks, I did upload this new version in Debian. Let's hope they do a VLC release soon. I close this issue.
