### ISSUE TITLE
Change license to MIT (expat)

### ISSUE THREAD

**Issue by i-rinat** [i-rinat/libvdpau-va-gl#52]
Hi. I'm going to change code license to MIT (https://www.debian.org/legal/licenses/mit). Or at least part of the code.

@mar-kolya, @vincentbernat, @Red54, @elenril, as you made changes, I need to ask you if you don't mind changing licensing terms of your contributions. Please notify, if you are agree (or not) with the license change.

**Comment by mar-kolya** [comment]
No objections.

**Comment by vincentbernat** [comment]
No problem for me either.

**Comment by elenril** [comment]
Fine with me as well.

**Comment by i-rinat** [comment]
@mar-kolya, @vincentbernat, @elenril, Thank you!

**Comment by Red54** [comment]
All right.

**Comment by i-rinat** [comment]
@Red54, Thank you!

**Comment by i-rinat** [comment]
Changed in https://github.com/i-rinat/libvdpau-va-gl/commit/4d0710a546c1c6510f3d03a6be4bdb46c6fff510
