### ISSUE TITLE
Build failure with clang/libc++ on Linux

### ISSUE THREAD

**Issue by elkrejzi** [i-rinat/libvdpau-va-gl#57]
libvdpau-va-gl-0.4.0 fails to build with clang with the following error:

`/home/armin/src/libvdpau-va-gl-0.4.0/src/api-device.cc:60:14: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'`

The fix for this is to add `#include <string>` to the mentioned file.

**Comment by i-rinat** [comment]
Thanks for report! Added in 416416d0e247d3ca57e093d977050450038ded71.

**Comment by i-rinat** [comment]
v0.4.1 now have this commit included.
