### ISSUE TITLE
GPU memory leak in VLC on Intel

### ISSUE THREAD

**Issue by gnoutchd** [i-rinat/libvdpau-va-gl#58]
VLC users with Intel GPUs have been encountering rapid memory exhaustion when trying to play videos using the VDPAU output driver (which appears to be the default now).  Switching to a different driver (e.g. the XVideo one) seems to "fix" this problem.

This has been reported on VLC bug trackers, but their triagers have pointed their fingers at libvdpau-va-gl and have closed their bugs:

- <https://trac.videolan.org/vlc/ticket/16749>
- <https://trac.videolan.org/vlc/ticket/16731>

I've been encountering this issue on a Intel 965GM on Debian testing (with vlc 2.2.4-2 and libvdpau-va-gl 0.3.6-1).

For what it's worth, here's what my own digging has turned up:

- Monitoring `/proc/meminfo` shows that the leaked memory is accounted as Shmem.

- Monitoring `/sys/kernel/debug/dri/*/i915_gem_objects` suggests that the vlc process leaks gem objects at a steady rate equal to the playing video's framerate (playing a 24 fps video leaks 24 objects per second, 30 fps -> 30 objects/second).  The leak continues at the same rate even when I pause the video, but it does stop when I freeze vlc with SIGSTOP (Ctrl+z).

**Comment by gnoutchd** [comment]
Tried again with libvdpau-va-gl 0.4.0-1.  Still affected.

Debian bug: <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820822>.

**Comment by i-rinat** [comment]
There was a GL framebuffer object leak in video surface handling code. Fixed in a860f26f1d7b0c0199e39b192c0ada7599d69e96.

Could you test again with libvdpau-va-gl built from git master branch, please?

**Comment by i-rinat** [comment]
So far VLC is the only application, that creates and destroys video surfaces for every frame. All other apps just created a number of video surfaces and reused them. That's why I never noticed resource leak before.

**Comment by gnoutchd** [comment]
I can confirm that commit a860f26 fixes this bug.  Thanks!
