### ISSUE TITLE
When playing .webm files with video-output default (VDPAU) VLC ends up consuming a lot of RAM (using lib64vdpau-va-gl1-0.4.0-1.mga6 on Intel Graphics)

### ISSUE THREAD

**Issue by shlomif** [i-rinat/libvdpau-va-gl#60]
Hi!

I originally reported it here - https://trac.videolan.org/vlc/ticket/17241 . Copying from it:

On my Mageia x86-64 v6 system running on a Core i3 machine with the built-in Intel Graphics HD (with vdpau-va-gl upgraded to lib64vdpau-va-gl1-0.4.0-1.mga6 ), when running VLC or cvlc of either the /usr/bin one or one compiled from vlc-git-3.0 sources, then the RAM consumption of the system quickly increases while playing a .webm file and is released after I exit VLC. It doesn't happen w --novideo or in mpv or when using the XCB video-output-method. I'll attach a VLC log soon. Note that I don't see this RAM increase in the process size - only in the total memory consumption statistics of htop (but I see it in the VIRT column).

After I exit VLC the memory becomes fine. This also happens in a new UNIX user account using JWM.

It also doesn't happen with --vout opengl and there are links to some sample files in the VLC bug (and it happens with all .webm and .mp4 files I tried). I'll appreciate any insights you can provide in solving this bug, but note that it may be in VLC itself.

**Comment by i-rinat** [comment]
This is a bug in  libvdpau-va-gl code. It was also reported in #58 and fixed in a860f26f1d7b0c0199e39b192c0ada7599d69e96.

I think I wanted to add some more changes before marking with v0.4.1 tag, but that never happened. I'll make v0.4.1 release in a couple of minutes.

**Comment by i-rinat** [comment]
> v0.4.1

released

**Comment by shlomif** [comment]
Thanks @i-rinat! I'm going to check out the new release, upgrade and report my findings.

**Comment by shlomif** [comment]
@i-rinat: thanks! After the upgrade, everything seems to be working fine now in VLC except for one problematic .mp4 file that refuses to play with --vout vdpau, but I guess that is a different issue. Closing as FIXED.

**Comment by i-rinat** [comment]
Please close bug in VLC's bugtracker as well. That's not their bug.
